In [1]:
#Let's import the dependencies
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn import preprocessing
import matplotlib.pyplot as plt

In [2]:
#Call the database

wd = "C:/Users/avalo/OneDrive/Documentos/tec_documentos_plataforma/facebook_work/facebook_mock.csv"

df = pd.read_csv(wd)
df.head()

,Page.total.likes,Type,Category,Post.Month,Post.Weekday,Post.Hour,Paid,LPost.Tot.Reach,LPost.Tot.Impressions,Lifetime.Engaged.Users,LPost.Consumers,LPost.Consumptions,LPost.Liked.Page.Impressions,LPost.Liked.Page.Reach,LPeople.Post.Like...Engange,comment,like,share,Total.Interactions,Clus_km
0,139441,Photo,2,12,4,3,0,2752,5091,178,109,159,3078,1640,119,4,79,17,100,0
1,139441,Status,2,12,3,10,0,10460,19057,1457,1361,1674,11710,6112,1108,5,130,29,164,0
2,139441,Photo,3,12,3,3,0,2413,4373,177,113,154,2812,1503,132,0,66,14,80,0
3,139441,Photo,2,12,2,10,1,50128,87991,2211,790,1119,61027,32048,1386,58,1572,147,1777,1
4,139441,Photo,2,12,2,3,0,7244,13594,671,410,580,6228,3200,396,19,325,49,393,1

In [8]:
#Let's see how many columns (features) we have and how many rows (observations)
df.shape

(716, 20)

In [4]:
groups_df = df.groupby(["Type", "Clus_km"])

In [6]:
names = ["Page.total.likes", "Category","LPost.Tot.Reach", "LPost.Tot.Impressions", "Lifetime.Engaged.Users", "LPost.Consumers",
         "LPost.Consumptions", "LPost.Liked.Page.Impressions", "LPost.Liked.Page.Reach",
         "LPeople.Post.Like...Engange", "comment","like","share"]

In [8]:
medias = groups_df[names].mean()
medias

                Page.total.likes  Category  LPost.Tot.Reach  \
Type   Clus_km
Link   0           116363.181818  1.136364     18544.590909
Photo  0           122108.407008  1.894879     10407.447439
       1           125283.013575  2.122172     38197.348416
Status 0           132810.631579  2.026316     11807.842105
       1           129845.684211  2.078947     35048.473684
Video  0           138372.333333  1.000000     22056.000000
       1           120822.782609  1.826087     42555.391304

                LPost.Tot.Impressions  Lifetime.Engaged.Users  \
Type   Clus_km
Link   0                 28725.454545              342.818182
Photo  0                 23591.646900              695.619946
       1                 64555.633484             1806.769231
Status 0                 21731.052632             1767.473684
       1                 65355.684211             2312.973684
Video  0                 41149.000000              705.666667
       1                 84037.391304             1780.913043

                LPost.Consumers  LPost.Consumptions  \
Type   Clus_km
Link   0             292.681818          374.090909
Photo  0             624.854447         1219.021563
       1            1410.113122         2374.479638
Status 0            1691.736842         2339.368421
       1            1748.473684         3256.105263
Video  0             645.666667          978.000000
       1            1860.826087         2410.956522

                LPost.Liked.Page.Impressions  LPost.Liked.Page.Reach  \
Type   Clus_km
Link   0                        11148.590909             6544.363636
Photo  0                        12548.614555             4649.339623
       1                        37043.244344            16823.230769
Status 0                        17464.052632             9329.526316
       1                        33528.078947            17875.657895
Video  0                        26063.000000            11813.333333
       1                        44763.695652            18039.913043

                LPeople.Post.Like...Engange    comment        like      share
Type   Clus_km
Link   0                         210.545455   2.818182   73.318182  12.909091
Photo  0                         428.490566   3.614555  108.458221  18.884097
       1                        1146.570136  24.932127  588.262443  69.927602
Status 0                        1534.000000   6.368421  130.131579  23.894737
       1                        1375.842105  19.736842  527.947368  70.000000
Video  0                         456.333333   7.333333  102.333333  13.333333
       1                        1001.521739  21.956522  463.956522  77.130435

In [ ]:
medias.reset_index(drop=True, inplace=True)
medias

In [13]:
ids = list(range(1,8))
ids

[1, 2, 3, 4, 5, 6, 7]

In [15]:
medias["ids"]=ids
medias

                Page.total.likes  Category  LPost.Tot.Reach  \
Type   Clus_km
Link   0           116363.181818  1.136364     18544.590909
Photo  0           122108.407008  1.894879     10407.447439
       1           125283.013575  2.122172     38197.348416
Status 0           132810.631579  2.026316     11807.842105
       1           129845.684211  2.078947     35048.473684
Video  0           138372.333333  1.000000     22056.000000
       1           120822.782609  1.826087     42555.391304

                LPost.Tot.Impressions  Lifetime.Engaged.Users  \
Type   Clus_km
Link   0                 28725.454545              342.818182
Photo  0                 23591.646900              695.619946
       1                 64555.633484             1806.769231
Status 0                 21731.052632             1767.473684
       1                 65355.684211             2312.973684
Video  0                 41149.000000              705.666667
       1                 84037.391304             1780.913043

                LPost.Consumers  LPost.Consumptions  \
Type   Clus_km
Link   0             292.681818          374.090909
Photo  0             624.854447         1219.021563
       1            1410.113122         2374.479638
Status 0            1691.736842         2339.368421
       1            1748.473684         3256.105263
Video  0             645.666667          978.000000
       1            1860.826087         2410.956522

                LPost.Liked.Page.Impressions  LPost.Liked.Page.Reach  \
Type   Clus_km
Link   0                        11148.590909             6544.363636
Photo  0                        12548.614555             4649.339623
       1                        37043.244344            16823.230769
Status 0                        17464.052632             9329.526316
       1                        33528.078947            17875.657895
Video  0                        26063.000000            11813.333333
       1                        44763.695652            18039.913043

                LPeople.Post.Like...Engange    comment        like      share  \
Type   Clus_km
Link   0                         210.545455   2.818182   73.318182  12.909091
Photo  0                         428.490566   3.614555  108.458221  18.884097
       1                        1146.570136  24.932127  588.262443  69.927602
Status 0                        1534.000000   6.368421  130.131579  23.894737
       1                        1375.842105  19.736842  527.947368  70.000000
Video  0                         456.333333   7.333333  102.333333  13.333333
       1                        1001.521739  21.956522  463.956522  77.130435

                ids
Type   Clus_km
Link   0          1
Photo  0          2
       1          3
Status 0          4
       1          5
Video  0          6
       1          7

In [19]:
medias.reset_index(drop=True, inplace=True)
medias

,Page.total.likes,Category,LPost.Tot.Reach,LPost.Tot.Impressions,Lifetime.Engaged.Users,LPost.Consumers,LPost.Consumptions,LPost.Liked.Page.Impressions,LPost.Liked.Page.Reach,LPeople.Post.Like...Engange,comment,like,share,ids
0,116363.181818,1.136364,18544.590909,28725.454545,342.818182,292.681818,374.090909,11148.590909,6544.363636,210.545455,2.818182,73.318182,12.909091,1
1,122108.407008,1.894879,10407.447439,23591.646900,695.619946,624.854447,1219.021563,12548.614555,4649.339623,428.490566,3.614555,108.458221,18.884097,2
2,125283.013575,2.122172,38197.348416,64555.633484,1806.769231,1410.113122,2374.479638,37043.244344,16823.230769,1146.570136,24.932127,588.262443,69.927602,3
3,132810.631579,2.026316,11807.842105,21731.052632,1767.473684,1691.736842,2339.368421,17464.052632,9329.526316,1534.000000,6.368421,130.131579,23.894737,4
4,129845.684211,2.078947,35048.473684,65355.684211,2312.973684,1748.473684,3256.105263,33528.078947,17875.657895,1375.842105,19.736842,527.947368,70.000000,5
5,138372.333333,1.000000,22056.000000,41149.000000,705.666667,645.666667,978.000000,26063.000000,11813.333333,456.333333,7.333333,102.333333,13.333333,6
6,120822.782609,1.826087,42555.391304,84037.391304,1780.913043,1860.826087,2410.956522,44763.695652,18039.913043,1001.521739,21.956522,463.956522,77.130435,7

In [23]:
medias_r =medias[names].apply(np.ceil)
medias_r

,Page.total.likes,Category,LPost.Tot.Reach,LPost.Tot.Impressions,Lifetime.Engaged.Users,LPost.Consumers,LPost.Consumptions,LPost.Liked.Page.Impressions,LPost.Liked.Page.Reach,LPeople.Post.Like...Engange,comment,like,share
0,116364.0,2.0,18545.0,28726.0,343.0,293.0,375.0,11149.0,6545.0,211.0,3.0,74.0,13.0
1,122109.0,2.0,10408.0,23592.0,696.0,625.0,1220.0,12549.0,4650.0,429.0,4.0,109.0,19.0
2,125284.0,3.0,38198.0,64556.0,1807.0,1411.0,2375.0,37044.0,16824.0,1147.0,25.0,589.0,70.0
3,132811.0,3.0,11808.0,21732.0,1768.0,1692.0,2340.0,17465.0,9330.0,1534.0,7.0,131.0,24.0
4,129846.0,3.0,35049.0,65356.0,2313.0,1749.0,3257.0,33529.0,17876.0,1376.0,20.0,528.0,70.0
5,138373.0,1.0,22056.0,41149.0,706.0,646.0,978.0,26063.0,11814.0,457.0,8.0,103.0,14.0
6,120823.0,2.0,42556.0,84038.0,1781.0,1861.0,2411.0,44764.0,18040.0,1002.0,22.0,464.0,78.0

In [25]:
medias_r.to_csv (r'C:\Users\avalo\OneDrive\Documentos\tec_documentos_plataforma\facebook_work\cases.csv', index = False, header=True)